#端口号
server:
  port: 8877

spring:
  application:
    name: wsm-demo #服务名
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@120.77.199.11:15221:HELOWIN
    username: phsms
    password: phsms_2019

# 配置mybatis-plus
mybatis-plus:
  # 配置扫描xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.study.model







